time = 8
#bucle until
until time >= 20 do # Mientras (until) time no sea mayor o igual que 20...
  puts "#{time} Hello" # imprimir el valor de time junto con un saludo...
  time += 1 # y sumar 1 al valor de time.
end